# Generated by Django 4.0.4 on 2022-06-30 06:07

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ChatUser',
                'verbose_name_plural': 'ChatUsers',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChatLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('response', models.CharField(max_length=1500)),
                ('tag', models.CharField(max_length=100)),
                ('asked_by', models.EmailField(max_length=254)),
                ('is_registered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ChatLog',
                'verbose_name_plural': 'ChatLogs',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=200)),
                ('uploadedFile', models.FileField(upload_to='Uploaded Files/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='InfoTable',
            fields=[
                ('ref_no', models.AutoField(primary_key=True, serialize=False)),
                ('model_no', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=200)),
                ('contract_potential', models.CharField(max_length=100)),
                ('ship_to_party', models.CharField(max_length=100)),
                ('bill_to_party', models.CharField(max_length=100)),
                ('ship_to_party_address_1', models.CharField(max_length=100)),
                ('ship_to_party_address_2', models.CharField(max_length=100)),
                ('ship_to_party_address_3', models.CharField(max_length=100)),
                ('ship_to_party_postcode', models.IntegerField(default=None, null=True)),
                ('ship_to_party_city_town', models.CharField(max_length=100)),
                ('ship_to_party_state', models.CharField(max_length=100)),
                ('ship_to_party_tel_no', models.CharField(max_length=100)),
                ('ship_to_party_fax_no', models.CharField(max_length=100)),
                ('ship_to_party_price_group', models.CharField(max_length=100)),
                ('ship_to_party_customer_group', models.CharField(max_length=100)),
                ('department_location', models.CharField(max_length=100)),
                ('person_in_charge', models.CharField(max_length=100)),
                ('commissioning_date', models.DateField(auto_now_add=True)),
                ('commissioning_reference_no', models.CharField(max_length=100)),
                ('agreement_reference_no', models.CharField(max_length=100, null=True)),
                ('warranty_period_start_date', models.DateField(auto_now_add=True)),
                ('warranty_period_end_date', models.DateField(auto_now_add=True)),
                ('total_no_of_servicing', models.IntegerField(default=None, null=True)),
                ('total_months_of_servicing', models.IntegerField(default=None, null=True)),
                ('plan_preventive_maintenance', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('warranty_type', models.CharField(max_length=100)),
                ('suspended', models.CharField(max_length=100)),
                ('ship_to_party_id', models.IntegerField(default=None, null=True)),
                ('ema_number', models.CharField(max_length=100)),
                ('ema_number_contract_start', models.CharField(max_length=100)),
                ('ema_number_contract_end', models.CharField(max_length=100)),
                ('ema_number_status_display', models.CharField(max_length=100)),
                ('ema_number_payment_mode_display', models.CharField(max_length=100)),
                ('model_no_model_number', models.CharField(max_length=100)),
                ('model_no_standardised_model_name', models.CharField(max_length=100)),
                ('model_no_business_segment_display', models.CharField(max_length=100)),
                ('model_no_business_product_display', models.CharField(max_length=100)),
                ('model_no_brand_display', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(auto_now_add=True)),
                ('bill_to_party_price_group_display', models.CharField(max_length=100)),
                ('bill_to_party_customer_group_display', models.CharField(max_length=100)),
                ('bill_to_party_customer_name', models.CharField(max_length=100)),
                ('ship_to_party_customer_name', models.CharField(max_length=100)),
                ('ema_number_contract_type_display', models.CharField(max_length=100)),
                ('ship_to_party_debtor_code', models.CharField(max_length=100)),
                ('bill_to_party_debtor_code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'InfoTable',
                'verbose_name_plural': 'InfoTables',
            },
        ),
        migrations.CreateModel(
            name='Patterns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None)),
                ('tag', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pattern',
                'verbose_name_plural': 'Patterns',
            },
        ),
    ]
